service:
  name: zombie-chat-be-broadcaster

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  stage: ${env:STAGE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

plugins:
  - serverless-webpack

functions:
  connect:
    handler: src/handler.connect
    timeout: 12
    memorySize: 256
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/handler.disconnect
    timeout: 12
    memorySize: 256
    events:
      - websocket:
          route: $disconnect
  broadcast:
    handler: src/handler.broadcast
    timeout: 6
    memorySize: 128
    events:
      - websocket:
          route: $default
